<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting=array (
  'site_name' => '云智慧',
  'site_domain' => 'http://www.dilicms.com/',
  'site_logo' => 'images/logo.jpg',
  'site_icp' => '',
  'site_terms' => '',
  'site_stats' => '',
  'site_footer' => '',
  'site_status' => '1',
  'site_close_reason' => '网站维护升级中......',
  'site_keyword' => '',
  'site_description' => '',
  'site_theme' => 'default',
  'attachment_url' => '/attachments',
  'attachment_dir' => 'attachments',
  'attachment_type' => '*.jpg;*.gif;*.png;*.doc;*.docx',
  'attachment_maxupload' => '209715200',
  'thumbs_preferences' => '[]',
);